config/routes.rb
Railcross::Application.routes.draw do
  devise_for :admins

  resources :patients do
    resources :appointements
  end

  root :to => 'patients#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/appointement.rb
class Appointement < ActiveRecord::Base
  attr_accessible :change_medication, :date, :notes, :prescriptions_attributes 

  belongs_to :patient
  has_many :prescriptions
  
  accepts_nested_attributes_for :prescriptions, :allow_destroy => true
  before_save :prescriptions_changed?

  def prescriptions_changed?
    return if self.patient.appointements.empty?

    lp = self.patient.last_appointement.prescriptions 
    tp = self.prescriptions

    return (self.change_medication = true)  if lp.size <=> tp.size

    # Note: for here on to the end of this method I am
    # ashamed of myself, for now the clock is ticking
    # and this is the fastest way to do this, not the most efficient
    lp = lp.order("description")
    tp = tp.order("description")
   
    # if the lists are of the same size then we need to go 
    # deeper and check every field
    lp.zip(tp).each do |lp, tp|
      administration_changed = lp.administration_time != tp.administration_time
      description_changed = lp.description != tp.description

      if administration_changed or description_changed
        self.change_medication = true
      end
    end
  end
end

app/models/medication.rb
class Medication < ActiveRecord::Base
  attr_accessible :administration_time, :description

  belongs_to :appointement
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :age, :alergys, :diseases, :identification_card_number, :name, :national_healthcare_number, :nationality, :sex, :appointements_attributes

  has_many :appointements
  has_many :prescriptions, :through => :appointements
  accepts_nested_attributes_for :appointements, :allow_destroy => true

  def last_appointement_date
    appointements.last.date
  end

  def last_appointement
    appointements.last
  end

  def new_appointement_with_last_prescription
    _la = self.appointements.last(:include => :prescriptions)
    _lp = _la.prescriptions unless _la.nil?

    new_appointement = self.appointements.new

    # if there is no last appointement there are no appointements
    # therefore there are no previously prescribed medication
    return new_appointement if _la.nil? or _lp.blank?
    
    # give it the same medication as the last appointement
    new_appointement.prescriptions = _lp.map(&:dup)

    new_appointement
  end
end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  attr_accessible :administration_time, :description

  belongs_to :appointement
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/appointements_controller.rb
class AppointementsController < ApplicationController
  before_filter :authenticate_admin!

  def new
    @patient = Patient.find(params[:patient_id])
    @appointement = @patient.new_appointement_with_last_prescription
  end

  def create
    @patient = Patient.find(params[:patient_id])
    @patient.appointements.build(params[:appointement])

    if @patient.save
      redirect_to patient_path(@patient) 
    else
      render :action => 'edit'
    end
  end

  def edit
    @patient = Patient.find(params[:patient_id])
    @appointement = @patient.appointements.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:patient_id])
    @appointement = @patient.appointements.find(params[:id])
    @appointement.update_attributes(params[:appointement])

    redirect_to patient_path(@patient)
  end

  def destroy
    @patient = Patient.find(params[:patient_id])
    @appointement = @patient.appointements.find(params[:id])
    @appointement.destroy

    redirect_to patient_path(@patient)
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_filter :authenticate_admin!

  def index
    @patients = Patient.all
  end

  def show
    @patient = Patient.find(params[:id])
    @appointements = @patient.appointements.order('created_at DESC')
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.create(params[:patient])
    redirect_to patient_path(@patient)
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    @patient.update_attributes(params[:patient])

    redirect_to patient_path(@patient)
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    redirect_to patients_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointements_helper.rb
module AppointementsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointements/_form.html.haml
%div.well
  = form_for [@patient, @appointement], :html => { :class => 'form-horizontal' } do |f|
    %fieldset
      %div.control-group
        = f.label :date, :class => 'control-label'
        %div.controls
          = f.datetime_select :date, {}, { :class => 'span1' }

      %div.control-group
        = f.label :notes, :class => 'control-label'
        %div.controls
          = f.text_area :notes, :rows => '2', :class => 'input-xlarge'

      %br

      %div.control-group
        %div.controls
          = f.fields_for :prescriptions do |prescription_form| 
            %div.form-inline
              = render 'prescription_fields', :f => prescription_form
          %div.control-group
            = link_to_add_association "Add Prescription", f, :prescriptions
      
      %div.form-actions
        = f.submit :class => 'btn btn-primary' 
        = link_to 'Cancel', :back, :class => 'btn btn-secondary'

app/views/appointements/_prescription_fields.html.haml
%div.nested-fields
  %p
    = f.select :administration_time, %w(breakfast lunch dinner evening), {}, { :class => 'span2' }
    = f.text_field :description, :placeholder => 'Medication'
    = link_to_remove_association 'Delete', f

app/views/appointements/edit.html.haml
%div.page-header
  %h1 Edit Appointement

= render 'form'

app/views/appointements/new.html.haml
%div.page-header
  %h1 New Appointement

= render 'form' 

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title 
      Railcross
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"   
    = csrf_meta_tags
%body
  = render :partial => 'shared/header.html.haml'
  %div.container
    = yield 

app/views/patients/_form.html.haml
%div.well
  = form_for @patient, :html => { :class => 'form-horizontal' } do |f|
    %fieldset
      %div.control-group
        = f.label :name, :class => 'control-label'
        %div.controls
          = f.text_field :name, :class => 'input-xlarge'

      %div.control-group
        = f.label :age, :class => 'control-label'
        %div.controls
          = f.number_field :age, :class => 'span1'

      %div.control-group
        = f.label :gender, :class => 'control-label'
        %div.controls
          = f.select :sex, %w(male female)

      %div.control-group
        = f.label :bi, :class => 'control-label'
        %div.controls
          = f.number_field :identification_card_number

      %div.control-group
        = f.label :national_healthcare, :class => 'control-label'
        %div.controls
          = f.number_field :national_healthcare_number

      %div.control-group
        = f.label :country, :class => 'control-label'
        %div.controls
          = f.country_select :nationality, ['Portugal']

      %div.control-group
        = f.label :diseases, :class => 'control-label'
        %div.controls
          = f.text_area :diseases, :rows => '2', :class => 'input-xlarge'

      %div.control-group
        = f.label :alergys, :class => 'control-label'
        %div.controls
          = f.text_area :alergys, :rows => '2', :class => 'input-xlarge'

      %div.form-actions
        = f.submit :class => 'btn btn-primary' 
        = link_to 'Cancel', :back, :class => 'btn btn-secondary'

app/views/patients/edit.html.haml
%div.page-header
  %h1 Edit Patient

= render 'form'

app/views/patients/index.html.haml
%div.page-header
  %h1 Patients

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th #
      %th Name
      %th Last Appointement
  %tbody
    - unless @patients.blank?
      - @patients.each do |patient|
        %tr{:onclick => "location.href='#{patient_path(patient)}'"}
          %td= patient.id
          %td= patient.name
          %td
            - if patient.appointements.blank?
              %span{:class=>'label label-info'} 
                %i{:class=>'icon-exclamation-sign'} 
                  No appointements made
            - else
              = time_ago_in_words(patient.last_appointement_date) 

= link_to 'Add Patient', new_patient_path, :class => 'btn btn-primary'

app/views/patients/new.html.haml
%div.page-header
  %h1 New Patient

= render 'form'

app/views/patients/show.html.haml
%div.row
  %div.span6
    %h1
      = @patient.name
      %small
        = "#{@patient.sex},"
        = "#{@patient.age} years old"
  %div.span6
    = link_to edit_patient_path(@patient), :class => 'btn' do
      %i{ :class => 'icon-pencil' }
      edit
    = link_to patient_path(@patient), :class => 'btn', :method => :delete, :confirm => 'Are you sure you want to delete this patient?' do
      %i{ :class => 'icon-trash' }
      delete


%div.row
  %div.span12
    %dl.dl-horizontal
      %dt Identification Number
      %dd= @patient.identification_card_number

      %dt National Healthcare Number
      %dd= @patient.national_healthcare_number

      %dt Country
      %dd= @patient.nationality

      %dt Diseases
      %dd= @patient.diseases

      %dt Alergys
      %dd= @patient.alergys
      %hr

%div.row
  %div.span12
    %ul.thumbnails
      - unless @appointements.blank?
        - @appointements.each do |appointement|
          %li.span3
            %div.thumbnail.well
              %h5 
                =time_ago_in_words(appointement.date)
                - if appointement.change_medication
                  %i{ :class => 'icon-random pull-right' } 
              %br
              %p= appointement.notes
              %br
              %p
                = link_to 'edit', edit_patient_appointement_path(@patient, appointement), :class => 'btn btn-mini btn-info' 
                = link_to 'delete', patient_appointement_path(@patient, appointement), :confirm => 'Are you sure you want to delete this appointement', :method => :delete, :class => 'btn btn-mini btn-danger'
                
    = link_to 'Add Appointement', new_patient_appointement_path(@patient), :class => 'btn btn-primary'  

app/views/shared/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to 'railcross', root_path, :class => 'brand'

      - if admin_signed_in?      
        %ul.nav.pull-right
          %li.dropdown#account
            %a{ :href=>"#account", :class => "dropdown-toggle", 'data-toggle' => "dropdown" } 
              %i{ :class => "icon-user icon-white" }
              = current_admin.email
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to 'Settings', edit_admin_registration_path
              %li
                = link_to 'Logout', destroy_admin_session_path, :method => :delete 